### ISSUE TITLE
Light wave is out of phase on retina iPad

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#117]
While reviewing the code for #44 I observed that the light wave is out of phase on the retina iPad:

![image](https://cloud.githubusercontent.com/assets/679486/8971001/34477f9c-360a-11e5-889e-af0b48f781a4.png)

When I tested on Desktop Chrome on a non-retina device, I only saw cases with the waves in-phase, like so:

![image](https://cloud.githubusercontent.com/assets/679486/8971020/5abd10d8-360a-11e5-9253-a0e7aaced075.png)

Having these waves be in-phase is integral to the learning goals of the simulation.  I am not sure it is related to retina vs non-retina but thought it might be one possibility.  @ChandrashekarBemagoni can you look into this issue?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @samreid for verification

**Comment by samreid** [comment]
I published a fresh version for testing:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.16/bending-light_en.html

On the retina iPad3, the phase is incorrect:
![image](https://cloud.githubusercontent.com/assets/679486/9449897/d20c95de-4a62-11e5-8b37-8fefb28c2fc6.png)

**Comment by jonathanolson** [comment]
On Chrome/Win7, I'm seeing that the matching offset depends on screen size (increasing the width of the available area to the sim seems to change the offset, so I can make it match or not match).

See below:
![bending-light-mismatch](https://cloud.githubusercontent.com/assets/480878/9451246/cc6d5796-4a6a-11e5-8327-c426c635b132.PNG)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for verification

**Comment by samreid** [comment]
It looks like the window size and retina aspects are no longer an issue, thanks @ChandrashekarBemagoni!  On retina iPad, however, I still see a small wrinkle at the interface.  @ariel-phet can you please review it on a retina iPad and let me know if it is acceptable or not?  Here's a fresh version for testing:
http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.21/bending-light_en.html

**Comment by arouinfar** [comment]
@samreid, I took a look at this on the iPad 3 and iPad Air, and it looks good to me. Closing.
