### ISSUE TITLE
Laser behaves as if the source was enclosed in prisms

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/bending-light#62]
On the Prisms Screen if you bring a prism close enough to the diode the laser behaves as if it was completely enclosed in the medium.

Normal Distance:
![screen shot 2015-06-02 at 10 32 25 am](https://cloud.githubusercontent.com/assets/5631059/7941230/110c8960-0913-11e5-85b9-fffc71dd9e45.png)

Critical Distance:
![screen shot 2015-06-02 at 10 32 17 am](https://cloud.githubusercontent.com/assets/5631059/7941237/1b93bc28-0913-11e5-9dd3-c0193a5ffa27.png)

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://www.colorado.edu/physics/phet/dev/html/bending-light/1.0.0-dev.3/bending-light_en.html
Version: 1.0.0-dev.3 2015-05-31 01:07:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Language: en-US
Window: 1114x1235
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"comment":"# bending-light 1.0.0-dev.3 Sat May 30 2015 19:07:45 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"4875945b5eb9027d4994f6ffa990b664979c1d86","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"bending-light":{"sha":"e99296da4f6ca1fff8fc142e89c34f7352c87eb4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"60c6645455a0692ec65c701c462399822599b1ef","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"ee8f44af90bd8dfd7d13399ecb429348c94e8dd5","branch":"master"}}

**Comment by ChandrashekarBemagoni** [comment]
Fixed with  https://github.com/phetsims/kite/commit/0d61997d59a020553e367cbe0e936b53ffb35f9c commit. Assigning to @orejolaphet for verification

**Comment by arouinfar** [comment]
There still appears to be a critical distance at which the laser behaves like it is in the "Material" and not the "Environment". 
![image](https://cloud.githubusercontent.com/assets/8419308/8088845/7c30745a-0f61-11e5-9bcc-35528cd18901.png)

In the Java version, the laser behaves as though it is in the "Environment" so long as part of the beam is outside of the prism.
![image](https://cloud.githubusercontent.com/assets/8419308/8088940/1133ee60-0f62-11e5-86b7-02687656d82c.png)

Reassigning to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
This issue is no longer there in latest code. see  attached file 
![prisms](https://cloud.githubusercontent.com/assets/7919831/8107490/2cf643e0-1067-11e5-9506-692cf20d059e.gif)

**Comment by ChandrashekarBemagoni** [comment]
Please take latest code of https://github.com/phetsims/kite before test. Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Sorry about that, @ChandrashekarBemagoni. I had pulled bending-light but had forgotten to pull kite. It looks great! Closing.
