### ISSUE TITLE
Speed is not read in intensity meter for waves

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/bending-light#81]
Test device: iPad2 

Operating System: iOS 8.3

Browser: Safari

Problem description: The speed cannot be read in some parts of the light wave when there is also an intensity meter. I'm mentioning this because you can measure the speed in every part of a light ray with the intensity meter, so there is an inconsistency. 

Steps to reproduce: Take out intensity meter, place in light wave. Take out speed reader, drag to a part of the light wave that is over the intensity meter glass.

Severity: Minor

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/8044932/3da0e726-0ded-11e5-83c9-3ee2dd7678ff.png)

Doesn't happen for the ray:
![image](https://cloud.githubusercontent.com/assets/12610678/8044938/487fb56e-0ded-11e5-9fee-f53ed1d102f7.png)

Troubleshooting information (do not edit):
Name: Bending Light
URL: http://phettest.colorado.edu/git-dev/bending-light/bending-light_en.html
Version: 1.0.0-dev.3 (require.js)
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: undefined

**Comment by arouinfar** [comment]
This is also present in OSX 10.9.5/Chrome 43:
![image](https://cloud.githubusercontent.com/assets/8419308/8045121/7286da4e-0dee-11e5-892a-d87929b1c44c.png)

However, the issue does not exist in the Java version:
![image](https://cloud.githubusercontent.com/assets/8419308/8045130/7e93590c-0dee-11e5-8277-677e744eb495.png)

**Comment by ChandrashekarBemagoni** [comment]
In kite/js/segments/Line.js at line 155  s is distance of intersection point from the ray position. s has to be more accurate if we dealing with small values. for more information See https://github.com/phetsims/kite/issues/47. 
On resolved https://github.com/phetsims/kite/issues/47  issue can fix bending light issues  https://github.com/phetsims/bending-light/issues/73 , https://github.com/phetsims/bending-light/issues/62 , https://github.com/phetsims/bending-light/issues/81

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/kite/commit/0d61997d59a020553e367cbe0e936b53ffb35f9c . Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Looks great! Closing.

**Comment by arouinfar** [comment]
I accidentally I was responding to #82, so reopening the issue. The problem still persists.

Even if the speed sensor is at the exact location of the ray (center of the wave), it does will not read the speed in wave mode. In ray mode:
![image](https://cloud.githubusercontent.com/assets/8419308/8088670/5709d79e-0f60-11e5-9ec6-1437798ba65d.png)

Switching to wave, but leaving sensors in place:
![image](https://cloud.githubusercontent.com/assets/8419308/8088661/46c5f82c-0f60-11e5-8f96-bd8e94886469.png)

In the Java version, the speed sensor does not need to be located in the exact center of the wave. For example, the speed is being read in wave mode:
![image](https://cloud.githubusercontent.com/assets/8419308/8088699/8b49b420-0f60-11e5-9b6a-462e28860d39.png)
Switching to ray mode reveals that the sensor was not centrally located in the wave in the scenario above.
![image](https://cloud.githubusercontent.com/assets/8419308/8088708/969a41aa-0f60-11e5-807b-2a2780349ddb.png)

**Comment by ChandrashekarBemagoni** [comment]
These issue no longer there in latest code. please see attached gif file. 
![moretoolsissue](https://cloud.githubusercontent.com/assets/7919831/8107375/5f1cc534-1066-11e5-8f0d-df1d94401792.gif)

**Comment by ChandrashekarBemagoni** [comment]
Assigning to @arouinfar for verification

**Comment by arouinfar** [comment]
Thanks, @ChandrashekarBemagoni! Everything looks good. Closing.
