### ISSUE TITLE
Word order in internationalization, use StringUtils.format

### ISSUE THREAD

**Issue by samreid** [phetsims/bending-light#95]
During #44 I noticed this line of code:

```js
labelText.text = Util.toFixed( velocity.magnitude() / BendingLightConstants.SPEED_OF_LIGHT, 2 ) + " " + c_units;
```

This should be internationalized using a pattern with {0} and {1} substitutions so that translators can specify the ordering of the number and the text, and the whitespace.  See StringUtils.format for documentation.

**Comment by samreid** [comment]
Also, once this is fixed, there should no longer be any " characters (formerly used for the whitespace).

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
The fix above looks good.  I'm still seeing two occurrences of string concatenation that should be changed to use StringUtils.format.

LaserView.js has this line:
```js
var wavelengthValueText = new Text( this.laserWavelengthProperty.get() + ' ' + units_nmString );
```
and LaserControlPanelNode has this line:
```js
var wavelengthValueText = new Text( this.wavelengthProperty.get() + ' ' + units_nmString );
```

Both of those should also be generalized using StringUtils.format.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @samreid for review

**Comment by samreid** [comment]
Looks great, thanks.  Closing.
